import React, { useState } from 'react';
import { useInventory } from '../context/InventoryContext';
import { 
  Sparkles, 
  Send, 
  Copy, 
  Download, 
  Calendar, 
  CloudSun, 
  Users, 
  ShieldCheck, 
  CheckCircle2, 
  TrendingUp, 
  FileSpreadsheet, 
  Clock, 
  AlertCircle,
  Truck,
  ExternalLink
} from 'lucide-react';
import * as XLSX from 'xlsx';
import { format, addDays, parseISO } from 'date-fns';
import confetti from 'canvas-confetti';

export const AiOrderPlannerTab = () => {
  const { 
    items, 
    suppliers,
    dailyLogs, 
    selectedDate, 
    currency, 
    generateAiOrderForecast 
  } = useInventory();

  // Next day default
  const tomorrowDateStr = format(addDays(parseISO(selectedDate), 1), 'yyyy-MM-dd');
  const [targetDate, setTargetDate] = useState(tomorrowDateStr);
  const [selectedSupplierId, setSelectedSupplierId] = useState(suppliers[0]?.id || 'sup-1');
  const [weatherCondition, setWeatherCondition] = useState('normal'); // 'normal' | 'rain' | 'hot'
  const [specialSurgePercent, setSpecialSurgePercent] = useState(0); // 0% to 50%
  const [safetyBufferPercent, setSafetyBufferPercent] = useState(25); // 15% to 40%
  const [customQuantities, setCustomQuantities] = useState({});
  const [toastMessage, setToastMessage] = useState(null);

  // Weather multiplier
  let weatherMultiplier = 1.0;
  if (weatherCondition === 'rain') weatherMultiplier = 1.15; // Rain boosts delivery orders
  if (weatherCondition === 'hot') weatherMultiplier = 0.95;

  const activeSupplier = suppliers.find(s => s.id === selectedSupplierId) || suppliers[0];

  // Generate AI forecast
  const baseForecast = generateAiOrderForecast(targetDate, {
    weatherMultiplier,
    isSpecialEvent: specialSurgePercent > 0,
    targetSafetyDays: (1 + safetyBufferPercent / 100)
  });

  // Apply custom edits if user overrides any quantity
  const finalRecommendations = baseForecast.recommendations.map(rec => {
    const overrideVal = customQuantities[rec.item.id];
    const orderKg = overrideVal !== undefined ? parseFloat(overrideVal) || 0 : rec.recommendedOrderKg;
    const estCost = Math.round(orderKg * rec.item.defaultCostPerUnit);

    return {
      ...rec,
      recommendedOrderKg: orderKg,
      estimatedCost: estCost,
      isOverridden: overrideVal !== undefined
    };
  });

  const totalOrderKg = Number(finalRecommendations.reduce((a, b) => a + b.recommendedOrderKg, 0).toFixed(1));
  const totalOrderCost = Math.round(finalRecommendations.reduce((a, b) => a + b.estimatedCost, 0));

  // Formatted WhatsApp Purchase Order
  const formattedSupplierWhatsAppMsg = `*PURCHASE ORDER FOR ${format(parseISO(targetDate), 'dd-MMM-yyyy').toUpperCase()} (${baseForecast.dayOfWeek.toUpperCase()})*\n` +
    `🏢 *The Tandoor & Grill Kitchen*\n` +
    `🚚 Supplier: ${activeSupplier.name}\n` +
    `⏰ Delivery Time: By 08:30 AM Tomorrow\n\n` +
    `📦 *Fresh Poultry Cuts Required:*\n` +
    finalRecommendations.filter(r => r.recommendedOrderKg > 0).map((r, i) => `${i + 1}. ${r.item.name}: *${r.recommendedOrderKg} ${r.item.unit}*`).join('\n') +
    `\n\n📊 Total Volume: *${totalOrderKg} kg* | Est. Invoice: *${currency}${totalOrderCost.toLocaleString()}*\n` +
    `⚠️ Note: Please ensure temperature < 4°C with invoice slip. Delivery receiver: Rajesh (08:30 AM).`;

  // WhatsApp Web / App link
  const whatsAppPhone = activeSupplier?.whatsappNumber || '919820144552';
  const whatsAppLink = `https://wa.me/${whatsAppPhone}?text=${encodeURIComponent(formattedSupplierWhatsAppMsg)}`;

  // Copy to clipboard
  const handleCopy = () => {
    navigator.clipboard.writeText(formattedSupplierWhatsAppMsg);
    setToastMessage('📋 Purchase Order copied! Ready to paste into WhatsApp.');
    confetti({ particleCount: 35, spread: 50 });
    setTimeout(() => setToastMessage(null), 3000);
  };

  // Export Excel PO
  const handleExportExcel = () => {
    const wsData = [
      ['PURCHASE ORDER - THE TANDOOR & GRILL KITCHEN'],
      ['Target Delivery Date:', targetDate, 'Day of Week:', baseForecast.dayOfWeek],
      ['Supplier:', activeSupplier.name, 'Contact:', activeSupplier.contactPerson],
      ['Generated by:', 'PoultryPulse AI Demand Engine', 'Timestamp:', new Date().toLocaleString()],
      [],
      ['Item Name', 'Category', 'Current Stock (kg)', 'Forecast Demand (kg)', 'Order Qty (kg)', 'Unit Price', 'Total Cost']
    ];

    finalRecommendations.forEach(r => {
      wsData.push([
        r.item.name,
        r.item.category,
        r.currentStockKg,
        r.forecastedDemandKg,
        r.recommendedOrderKg,
        `${currency}${r.item.defaultCostPerUnit}`,
        `${currency}${r.estimatedCost}`
      ]);
    });

    wsData.push([]);
    wsData.push(['TOTALS', '', '', '', `${totalOrderKg} kg`, '', `${currency}${totalOrderCost.toLocaleString()}`]);

    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.aoa_to_sheet(wsData);
    XLSX.utils.book_append_sheet(wb, ws, 'Purchase Order');
    XLSX.writeFile(wb, `Purchase_Order_${targetDate}_${activeSupplier.name.replace(/\s+/g, '_')}.xlsx`);

    setToastMessage('📥 Purchase Order exported as Excel spreadsheet!');
    setTimeout(() => setToastMessage(null), 3000);
  };

  return (
    <div className="space-y-6">
      {/* Toast Alert */}
      {toastMessage && (
        <div className="fixed top-6 right-6 z-50 bg-emerald-600 text-white font-bold px-4 py-3 rounded-xl shadow-2xl flex items-center gap-2 border border-emerald-400 animate-bounce">
          <CheckCircle2 className="w-5 h-5" />
          <span>{toastMessage}</span>
        </div>
      )}

      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-slate-900/80 border border-slate-800 p-5 rounded-2xl">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-2xl bg-amber-500/20 border border-amber-500/30 flex items-center justify-center text-amber-400 text-2xl shadow-lg">
            🤖
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-lg font-bold text-white">AI Predictive Demand Forecasting & Smart PO Planner</h2>
              <span className="text-xs bg-amber-500 text-slate-950 font-extrabold px-2 py-0.5 rounded-full">
                AI Engine
              </span>
            </div>
            <p className="text-xs text-slate-400">
              Calculates tomorrow's exact raw chicken purchase order using historical weekday velocity, night stock counts, prep yields, and safety buffers.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleExportExcel}
            className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold border border-slate-700 transition-all"
          >
            <FileSpreadsheet className="w-3.5 h-3.5 text-emerald-400" />
            <span>Export Excel PO</span>
          </button>

          <a
            href={whatsAppLink}
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-2 px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs shadow-lg shadow-emerald-600/30 transition-all"
          >
            <Send className="w-3.5 h-3.5" />
            <span>Send WhatsApp to Supplier</span>
          </a>
        </div>
      </div>

      {/* AI Scenario Tuning Parameters Bar */}
      <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-5 space-y-4">
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <div className="flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-amber-400" />
            <h3 className="text-xs font-bold text-white uppercase tracking-wider">
              AI Forecast Scenario & Real-Time Parameter Tuner
            </h3>
          </div>
          <span className="text-[11px] text-slate-400">Tuned dynamically</span>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {/* Target Date */}
          <div className="bg-slate-800/40 p-3 rounded-xl border border-slate-700/60">
            <label className="text-[10px] text-slate-400 font-bold block mb-1">Target Order Date</label>
            <input
              type="date"
              value={targetDate}
              onChange={(e) => setTargetDate(e.target.value)}
              className="w-full bg-slate-900 text-xs font-semibold text-white border border-slate-700 rounded-lg p-1.5 focus:outline-none focus:border-amber-500"
            />
            <span className="text-[10px] text-amber-400 mt-1 block font-mono">
              Day: {baseForecast.dayOfWeek}
            </span>
          </div>

          {/* Supplier */}
          <div className="bg-slate-800/40 p-3 rounded-xl border border-slate-700/60">
            <label className="text-[10px] text-slate-400 font-bold block mb-1">Poultry Supplier</label>
            <select
              value={selectedSupplierId}
              onChange={(e) => setSelectedSupplierId(e.target.value)}
              className="w-full bg-slate-900 text-xs font-semibold text-white border border-slate-700 rounded-lg p-1.5 focus:outline-none focus:border-amber-500"
            >
              {suppliers.map(s => (
                <option key={s.id} value={s.id}>{s.name}</option>
              ))}
            </select>
            <span className="text-[10px] text-slate-400 mt-1 block">Lead time: {activeSupplier.leadTimeHours} hrs</span>
          </div>

          {/* Weather Impact */}
          <div className="bg-slate-800/40 p-3 rounded-xl border border-slate-700/60">
            <label className="text-[10px] text-slate-400 font-bold block mb-1">Weather Forecast</label>
            <select
              value={weatherCondition}
              onChange={(e) => setWeatherCondition(e.target.value)}
              className="w-full bg-slate-900 text-xs font-semibold text-white border border-slate-700 rounded-lg p-1.5 focus:outline-none focus:border-amber-500"
            >
              <option value="normal">☀️ Clear / Normal Day (1.0x)</option>
              <option value="rain">🌧️ Heavy Monsoon (+15% delivery surge)</option>
              <option value="hot">🔥 Extreme Heat (-5% dine-in)</option>
            </select>
            <span className="text-[10px] text-slate-400 mt-1 block">Applies delivery demand delta</span>
          </div>

          {/* Safety Stock Buffer */}
          <div className="bg-slate-800/40 p-3 rounded-xl border border-slate-700/60">
            <div className="flex items-center justify-between mb-1">
              <label className="text-[10px] text-slate-400 font-bold">Safety Stock Cushion</label>
              <span className="text-[10px] font-mono text-amber-400 font-bold">+{safetyBufferPercent}%</span>
            </div>
            <input
              type="range"
              min="10"
              max="40"
              step="5"
              value={safetyBufferPercent}
              onChange={(e) => setSafetyBufferPercent(parseInt(e.target.value))}
              className="w-full accent-orange-500 cursor-pointer"
            />
            <span className="text-[10px] text-slate-400 mt-1 block">Protects against sudden 8 PM rush</span>
          </div>
        </div>
      </div>

      {/* AI Suggested PO Summary Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <div className="bg-gradient-to-br from-slate-900 to-amber-950/30 border border-amber-500/30 p-4 rounded-xl">
          <span className="text-[10px] uppercase font-bold text-amber-400 block">AI Recommended Total Order</span>
          <div className="flex items-baseline gap-1 mt-1">
            <span className="text-3xl font-extrabold text-white">{totalOrderKg}</span>
            <span className="text-sm font-bold text-slate-400">KG</span>
          </div>
          <span className="text-[10px] text-slate-300">Ready for {baseForecast.dayOfWeek} service</span>
        </div>

        <div className="bg-slate-900/80 border border-slate-800 p-4 rounded-xl">
          <span className="text-[10px] uppercase font-bold text-slate-400 block">Estimated PO Cost</span>
          <div className="flex items-baseline gap-1 mt-1">
            <span className="text-3xl font-extrabold text-emerald-400">{currency}{totalOrderCost.toLocaleString()}</span>
          </div>
          <span className="text-[10px] text-slate-400">Based on {activeSupplier.name} rates</span>
        </div>

        <div className="bg-slate-900/80 border border-slate-800 p-4 rounded-xl">
          <span className="text-[10px] uppercase font-bold text-slate-400 block">Lead Time Deadline</span>
          <div className="flex items-baseline gap-1 mt-1">
            <span className="text-xl font-extrabold text-white">Send by 11:30 PM</span>
          </div>
          <span className="text-[10px] text-amber-400">For guaranteed 08:30 AM dispatch</span>
        </div>
      </div>

      {/* Item-by-Item AI Order Recommendation Table */}
      <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-5 space-y-4">
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <div>
            <h3 className="text-xs font-bold text-white uppercase tracking-wider">
              Itemized Purchase Recommendations (Editable)
            </h3>
            <p className="text-[11px] text-slate-400">You can adjust the suggested KG quantities before sending to supplier</p>
          </div>
          <button
            onClick={() => setCustomQuantities({})}
            className="text-[11px] font-bold text-amber-400 hover:text-amber-300"
          >
            Reset to AI Defaults
          </button>
        </div>

        <div className="space-y-2.5">
          <div className="grid grid-cols-12 text-[10px] font-bold text-slate-400 px-3 uppercase">
            <span className="col-span-4">Chicken Cut</span>
            <span className="col-span-2 text-right">In Stock (Night)</span>
            <span className="col-span-2 text-right">Predicted Demand</span>
            <span className="col-span-2 text-right">AI Suggested Order</span>
            <span className="col-span-2 text-right">Est. Cost</span>
          </div>

          {finalRecommendations.map((rec) => (
            <div
              key={rec.item.id}
              className={`grid grid-cols-12 items-center p-3.5 rounded-xl border transition-all ${
                rec.isOverridden 
                  ? 'bg-amber-950/20 border-amber-500/40' 
                  : 'bg-slate-800/40 border-slate-700/60 hover:border-slate-600'
              }`}
            >
              {/* Item details */}
              <div className="col-span-4 flex items-center gap-2.5">
                <span className="text-xl">{rec.item.icon}</span>
                <div>
                  <div className="flex items-center gap-1.5">
                    <h4 className="text-xs font-bold text-white">{rec.item.name}</h4>
                    {rec.urgency === 'HIGH' && (
                      <span className="text-[9px] font-extrabold bg-red-500/20 text-red-400 px-1.5 py-0.2 rounded border border-red-500/30">
                        LOW PAR
                      </span>
                    )}
                  </div>
                  <p className="text-[10px] text-slate-400 mt-0.5 truncate max-w-xs">{rec.reason}</p>
                </div>
              </div>

              {/* In Stock */}
              <div className="col-span-2 text-right font-mono text-xs text-slate-300">
                {rec.currentStockKg} <span className="text-[10px] text-slate-500">kg</span>
              </div>

              {/* Forecast Demand */}
              <div className="col-span-2 text-right font-mono text-xs text-slate-300">
                {rec.forecastedDemandKg} <span className="text-[10px] text-slate-500">kg</span>
              </div>

              {/* Order Qty Input */}
              <div className="col-span-2 flex justify-end items-center gap-1">
                <input
                  type="number"
                  step="0.5"
                  min="0"
                  value={rec.recommendedOrderKg}
                  onChange={(e) => setCustomQuantities({
                    ...customQuantities,
                    [rec.item.id]: e.target.value
                  })}
                  className="w-20 bg-slate-900 border border-slate-700 rounded-lg px-2 py-1 text-xs text-amber-300 font-mono font-bold text-right focus:outline-none focus:border-amber-500"
                />
                <span className="text-[10px] text-slate-400 font-bold">kg</span>
              </div>

              {/* Cost */}
              <div className="col-span-2 text-right font-mono text-xs font-bold text-emerald-400">
                {currency}{rec.estimatedCost.toLocaleString()}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Supplier Formatted WhatsApp Message Preview */}
      <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-5 space-y-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Send className="w-4 h-4 text-emerald-400" />
            <h3 className="text-xs font-bold text-white uppercase tracking-wider">
              Supplier Purchase Order (WhatsApp Ready)
            </h3>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="text-xs text-slate-200 hover:text-white flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-800 border border-slate-700"
            >
              <Copy className="w-3.5 h-3.5 text-emerald-400" />
              <span>Copy PO Text</span>
            </button>

            <a
              href={whatsAppLink}
              target="_blank"
              rel="noopener noreferrer"
              className="text-xs font-bold text-white flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 shadow-md shadow-emerald-700/30"
            >
              <ExternalLink className="w-3.5 h-3.5" />
              <span>Open in WhatsApp</span>
            </a>
          </div>
        </div>

        <div className="bg-[#0b141a] p-4 rounded-xl border border-[#222e35] text-xs text-slate-200 font-mono whitespace-pre-line leading-relaxed">
          {formattedSupplierWhatsAppMsg}
        </div>
      </div>
    </div>
  );
};
