import React, { useState } from 'react';
import { useInventory } from '../context/InventoryContext';
import { AddVendorModal } from './AddVendorModal';
import { 
  Sparkles, 
  Send, 
  Copy, 
  Download, 
  Calendar, 
  CloudSun, 
  Users, 
  ShieldCheck, 
  CheckCircle2, 
  TrendingUp, 
  FileSpreadsheet, 
  Clock, 
  AlertCircle,
  Truck,
  ExternalLink,
  Plus
} from 'lucide-react';
import * as XLSX from 'xlsx';
import { format, addDays, parseISO } from 'date-fns';
import confetti from 'canvas-confetti';

export const AiOrderPlannerTab = () => {
  const { 
    items, 
    suppliers,
    dailyLogs, 
    selectedDate, 
    currency, 
    generateAiOrderForecast 
  } = useInventory();

  const [isAddVendorOpen, setIsAddVendorOpen] = useState(false);
  const tomorrowDateStr = format(addDays(parseISO(selectedDate), 1), 'yyyy-MM-dd');
  const [targetDate, setTargetDate] = useState(tomorrowDateStr);
  const [selectedSupplierId, setSelectedSupplierId] = useState(suppliers[0]?.id || 'sup-1');
  const [weatherCondition, setWeatherCondition] = useState('normal');
  const [specialSurgePercent, setSpecialSurgePercent] = useState(0);
  const [safetyBufferPercent, setSafetyBufferPercent] = useState(25);
  const [customQuantities, setCustomQuantities] = useState({});
  const [toastMessage, setToastMessage] = useState(null);

  let weatherMultiplier = 1.0;
  if (weatherCondition === 'rain') weatherMultiplier = 1.15;
  if (weatherCondition === 'hot') weatherMultiplier = 0.95;

  const activeSupplier = suppliers.find(s => s.id === selectedSupplierId) || suppliers[0];

  const baseForecast = generateAiOrderForecast(targetDate, {
    weatherMultiplier,
    isSpecialEvent: specialSurgePercent > 0,
    targetSafetyDays: (1 + safetyBufferPercent / 100)
  });

  const finalRecommendations = baseForecast.recommendations.map(rec => {
    const overrideVal = customQuantities[rec.item.id];
    const orderKg = overrideVal !== undefined ? parseFloat(overrideVal) || 0 : rec.recommendedOrderKg;
    const estCost = Math.round(orderKg * rec.item.defaultCostPerUnit);

    return {
      ...rec,
      recommendedOrderKg: orderKg,
      estimatedCost: estCost,
      isOverridden: overrideVal !== undefined
    };
  });

  const totalOrderKg = Number(finalRecommendations.reduce((a, b) => a + b.recommendedOrderKg, 0).toFixed(1));
  const totalOrderCost = Math.round(finalRecommendations.reduce((a, b) => a + b.estimatedCost, 0));

  // Formatted supplier WhatsApp message for 03:30 PM delivery
  const formattedSupplierWhatsAppMsg = `*INDUS WOK PURCHASE ORDER FOR ${format(parseISO(targetDate), 'dd-MMM-yyyy').toUpperCase()} (${baseForecast.dayOfWeek.toUpperCase()})*\n` +
    `🥢 *Restaurant: Indus Wok (Timings: 4:00 PM – 4:00 AM)*\n` +
    `🚚 Supplier: ${activeSupplier.name}\n` +
    `⏰ Delivery Requested: *By 03:30 PM* (Before 4:00 PM Opening)\n\n` +
    `📦 *Fresh Poultry Cuts Required:*\n` +
    finalRecommendations.filter(r => r.recommendedOrderKg > 0).map((r, i) => `${i + 1}. ${r.item.name}: *${r.recommendedOrderKg} ${r.item.unit}*`).join('\n') +
    `\n\n📊 Total Volume: *${totalOrderKg} kg* | Est. Invoice: *${currency}${totalOrderCost.toLocaleString()}*\n` +
    `⚠️ Note: Please ensure delivery temperature is below 4°C with fresh batch tags. Delivery receiver: Rajesh (03:30 PM).`;

  const whatsAppPhone = activeSupplier?.whatsappNumber || '919820144552';
  const whatsAppLink = `https://wa.me/${whatsAppPhone}?text=${encodeURIComponent(formattedSupplierWhatsAppMsg)}`;

  const handleCopy = () => {
    navigator.clipboard.writeText(formattedSupplierWhatsAppMsg);
    setToastMessage('📋 Purchase Order copied! Ready to paste into WhatsApp.');
    confetti({ particleCount: 35, spread: 50 });
    setTimeout(() => setToastMessage(null), 3000);
  };

  const handleExportExcel = () => {
    const wsData = [
      ['PURCHASE ORDER - INDUS WOK KITCHEN (TIMINGS: 4PM - 4AM)'],
      ['Target Delivery Date:', targetDate, 'Day of Week:', baseForecast.dayOfWeek],
      ['Supplier:', activeSupplier.name, 'Delivery Time:', '03:30 PM (Before 4:00 PM Opening)'],
      ['Generated by:', 'PoultryPulse AI Demand Engine (POS Correlated)', 'Timestamp:', new Date().toLocaleString()],
      [],
      ['Item Name', 'Category', 'Current Stock (kg)', 'Forecast Demand (kg)', 'Order Qty (kg)', 'Unit Price', 'Total Cost']
    ];

    finalRecommendations.forEach(r => {
      wsData.push([
        r.item.name,
        r.item.category,
        r.currentStockKg,
        r.forecastedDemandKg,
        r.recommendedOrderKg,
        `${currency}${r.item.defaultCostPerUnit}`,
        `${currency}${r.estimatedCost}`
      ]);
    });

    wsData.push([]);
    wsData.push(['TOTALS', '', '', '', `${totalOrderKg} kg`, '', `${currency}${totalOrderCost.toLocaleString()}`]);

    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.aoa_to_sheet(wsData);
    XLSX.utils.book_append_sheet(wb, ws, 'Purchase Order');
    XLSX.writeFile(wb, `Indus_Wok_PO_${targetDate}_${activeSupplier.name.replace(/\s+/g, '_')}.xlsx`);

    setToastMessage('📥 Purchase Order exported as Excel!');
    setTimeout(() => setToastMessage(null), 3000);
  };

  return (
    <div className="space-y-4 sm:space-y-6">
      <AddVendorModal
        isOpen={isAddVendorOpen}
        onClose={() => setIsAddVendorOpen(false)}
      />

      {toastMessage && (
        <div className="fixed top-6 right-6 z-50 bg-emerald-600 text-white font-bold px-4 py-3 rounded-xl shadow-2xl flex items-center gap-2 border border-emerald-400 animate-bounce">
          <CheckCircle2 className="w-5 h-5" />
          <span>{toastMessage}</span>
        </div>
      )}

      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 bg-slate-900/80 border border-slate-800 p-4 sm:p-5 rounded-2xl">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 sm:w-12 sm:h-12 rounded-xl sm:rounded-2xl bg-amber-500/20 border border-amber-500/30 flex items-center justify-center text-amber-400 text-xl sm:text-2xl shadow-lg shrink-0">
            🤖
          </div>
          <div>
            <div className="flex items-center gap-2 flex-wrap">
              <h2 className="text-base sm:text-lg font-bold text-white">AI Demand Forecast & Smart PO</h2>
              <span className="text-[10px] bg-amber-500 text-slate-950 font-extrabold px-2 py-0.5 rounded-full">
                4 PM – 4 AM Shift
              </span>
            </div>
            <p className="text-xs text-slate-400 hidden sm:block">
              Calculates purchase orders using Indus Wok late-night sales velocity, 4:00 AM closing stock, and prep yields.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2 w-full sm:w-auto">
          <button
            onClick={handleExportExcel}
            className="flex-1 sm:flex-none flex items-center justify-center gap-1.5 px-3 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold border border-slate-700 transition-all"
          >
            <FileSpreadsheet className="w-3.5 h-3.5 text-emerald-400" />
            <span>Excel PO</span>
          </button>

          <a
            href={whatsAppLink}
            target="_blank"
            rel="noopener noreferrer"
            className="flex-1 sm:flex-none flex items-center justify-center gap-1.5 px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 active:scale-95 text-white font-bold text-xs shadow-lg shadow-emerald-600/30 transition-all"
          >
            <Send className="w-3.5 h-3.5" />
            <span>Send PO WhatsApp</span>
          </a>
        </div>
      </div>

      {/* AI Scenario Tuning Parameters Bar */}
      <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-4 sm:p-5 space-y-3">
        <div className="flex items-center justify-between border-b border-slate-800 pb-2.5">
          <div className="flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-amber-400" />
            <h3 className="text-xs font-bold text-white uppercase tracking-wider">
              AI Forecast Scenario & Shift Parameters
            </h3>
          </div>
          <span className="text-[10px] text-slate-400 font-mono">Shift: 4:00 PM – 4:00 AM</span>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
          {/* Target Date */}
          <div className="bg-slate-800/40 p-3 rounded-xl border border-slate-700/60">
            <label className="text-[10px] text-slate-400 font-bold block mb-1">Target Shift Date</label>
            <input
              type="date"
              value={targetDate}
              onChange={(e) => setTargetDate(e.target.value)}
              className="w-full bg-slate-900 text-xs font-semibold text-white border border-slate-700 rounded-lg p-1.5 focus:outline-none focus:border-amber-500"
            />
            <span className="text-[10px] text-amber-400 mt-1 block font-mono">
              Day: {baseForecast.dayOfWeek}
            </span>
          </div>

          {/* Supplier */}
          <div className="bg-slate-800/40 p-3 rounded-xl border border-slate-700/60">
            <div className="flex items-center justify-between mb-1">
              <label className="text-[10px] text-slate-400 font-bold block">Poultry Supplier</label>
              <button
                type="button"
                onClick={() => setIsAddVendorOpen(true)}
                className="text-[9px] text-orange-400 hover:underline font-bold"
              >
                + Add Vendor
              </button>
            </div>
            <select
              value={selectedSupplierId}
              onChange={(e) => setSelectedSupplierId(e.target.value)}
              className="w-full bg-slate-900 text-xs font-semibold text-white border border-slate-700 rounded-lg p-1.5 focus:outline-none focus:border-amber-500"
            >
              {suppliers.map(s => (
                <option key={s.id} value={s.id}>{s.name}</option>
              ))}
            </select>
            <span className="text-[10px] text-slate-400 mt-1 block">Lead time: {activeSupplier.leadTimeHours} hrs</span>
          </div>

          {/* Weather Impact */}
          <div className="bg-slate-800/40 p-3 rounded-xl border border-slate-700/60">
            <label className="text-[10px] text-slate-400 font-bold block mb-1">Weather Condition</label>
            <select
              value={weatherCondition}
              onChange={(e) => setWeatherCondition(e.target.value)}
              className="w-full bg-slate-900 text-xs font-semibold text-white border border-slate-700 rounded-lg p-1.5 focus:outline-none focus:border-amber-500"
            >
              <option value="normal">☀️ Clear / Normal (1.0x)</option>
              <option value="rain">🌧️ Heavy Rain (+15% late-night delivery)</option>
              <option value="hot">🔥 Hot Weather (-5% dine-in)</option>
            </select>
          </div>

          {/* Safety Stock Buffer */}
          <div className="bg-slate-800/40 p-3 rounded-xl border border-slate-700/60">
            <div className="flex items-center justify-between mb-1">
              <label className="text-[10px] text-slate-400 font-bold">Safety Stock Cushion</label>
              <span className="text-[10px] font-mono text-amber-400 font-bold">+{safetyBufferPercent}%</span>
            </div>
            <input
              type="range"
              min="10"
              max="40"
              step="5"
              value={safetyBufferPercent}
              onChange={(e) => setSafetyBufferPercent(parseInt(e.target.value))}
              className="w-full accent-orange-500 cursor-pointer"
            />
            <span className="text-[10px] text-slate-400 mt-1 block">Protects against 1 AM rush</span>
          </div>
        </div>
      </div>

      {/* AI Suggested PO Summary Cards */}
      <div className="grid grid-cols-3 gap-2.5 sm:gap-4">
        <div className="bg-gradient-to-br from-slate-900 to-amber-950/30 border border-amber-500/30 p-3 sm:p-4 rounded-xl">
          <span className="text-[9px] uppercase font-bold text-amber-400 block">AI Recommended Total</span>
          <div className="flex items-baseline gap-1 mt-0.5">
            <span className="text-xl sm:text-3xl font-extrabold text-white">{totalOrderKg}</span>
            <span className="text-xs font-bold text-slate-400">KG</span>
          </div>
        </div>

        <div className="bg-slate-900/80 border border-slate-800 p-3 sm:p-4 rounded-xl">
          <span className="text-[9px] uppercase font-bold text-slate-400 block">Est. PO Invoice</span>
          <div className="flex items-baseline gap-1 mt-0.5">
            <span className="text-xl sm:text-3xl font-extrabold text-emerald-400 truncate">{currency}{totalOrderCost.toLocaleString()}</span>
          </div>
        </div>

        <div className="bg-slate-900/80 border border-slate-800 p-3 sm:p-4 rounded-xl">
          <span className="text-[9px] uppercase font-bold text-slate-400 block">Delivery Window</span>
          <div className="flex items-baseline gap-1 mt-0.5">
            <span className="text-xs sm:text-base font-extrabold text-white">03:30 PM</span>
          </div>
          <span className="text-[9px] text-amber-400">Before 4 PM Opening</span>
        </div>
      </div>

      {/* Item-by-Item AI Order Recommendation Table */}
      <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-4 sm:p-5 space-y-3">
        <div className="flex items-center justify-between border-b border-slate-800 pb-2.5">
          <h3 className="text-xs font-bold text-white uppercase tracking-wider">
            Itemized Purchase Recommendations
          </h3>
          <button
            onClick={() => setCustomQuantities({})}
            className="text-[10px] font-bold text-amber-400 hover:text-amber-300"
          >
            Reset to AI Defaults
          </button>
        </div>

        <div className="space-y-2">
          {finalRecommendations.map((rec) => (
            <div
              key={rec.item.id}
              className={`p-3 rounded-xl border transition-all space-y-2 ${
                rec.isOverridden 
                  ? 'bg-amber-950/20 border-amber-500/40' 
                  : 'bg-slate-800/40 border-slate-700/60 hover:border-slate-600'
              }`}
            >
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span className="text-base sm:text-lg">{rec.item.icon}</span>
                  <div>
                    <div className="flex items-center gap-1.5">
                      <h4 className="text-xs font-bold text-white">{rec.item.name}</h4>
                      {rec.urgency === 'HIGH' && (
                        <span className="text-[8px] font-extrabold bg-red-500/20 text-red-400 px-1 rounded border border-red-500/30">
                          LOW PAR
                        </span>
                      )}
                    </div>
                    <p className="text-[9px] text-slate-400 mt-0.5">{rec.reason}</p>
                  </div>
                </div>

                <div className="flex items-center gap-1.5 shrink-0">
                  <input
                    type="number"
                    step="0.5"
                    min="0"
                    value={rec.recommendedOrderKg}
                    onChange={(e) => setCustomQuantities({
                      ...customQuantities,
                      [rec.item.id]: e.target.value
                    })}
                    className="w-16 bg-slate-900 border border-slate-700 rounded-lg px-2 py-1 text-xs text-amber-300 font-mono font-bold text-center focus:outline-none focus:border-amber-500"
                  />
                  <span className="text-xs font-bold text-slate-400">kg</span>
                </div>
              </div>

              <div className="flex items-center justify-between text-[10px] pt-1.5 border-t border-slate-700/40 font-mono">
                <span className="text-slate-400">In Stock: {rec.currentStockKg}kg • Forecast: {rec.forecastedDemandKg}kg</span>
                <span className="font-bold text-emerald-400">{currency}{rec.estimatedCost.toLocaleString()}</span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Supplier Formatted WhatsApp Message Preview */}
      <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-4 sm:p-5 space-y-2.5">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Send className="w-4 h-4 text-emerald-400" />
            <h3 className="text-xs font-bold text-white uppercase tracking-wider">
              Supplier Purchase Order (03:30 PM Delivery)
            </h3>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="text-xs text-slate-200 hover:text-white flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-800 border border-slate-700"
            >
              <Copy className="w-3.5 h-3.5 text-emerald-400" />
              <span>Copy PO</span>
            </button>

            <a
              href={whatsAppLink}
              target="_blank"
              rel="noopener noreferrer"
              className="text-xs font-bold text-white flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 shadow-md shadow-emerald-700/30"
            >
              <ExternalLink className="w-3.5 h-3.5" />
              <span>Open in WhatsApp</span>
            </a>
          </div>
        </div>

        <div className="bg-[#0b141a] p-3 rounded-xl border border-[#222e35] text-[10px] sm:text-xs text-slate-200 font-mono whitespace-pre-line leading-relaxed">
          {formattedSupplierWhatsAppMsg}
        </div>
      </div>
    </div>
  );
};
